backend:
  name: github
  repo: zheever/vuepress
  branch: master # Branch to update (optional; defaults to master)
media_folder: "docs/.vuepress/public/images"
public_folder: "docs/.vuepress/dist/"
collections:
  - name: "doc" # Used in routes, e.g., /admin/collections/blog
    label: "Doc" # Used in the UI
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fileName}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "FILE Name", name: "fileName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "css" # Used in routes, e.g., /admin/collections/blog
    label: "Doc/css" # Used in the UI
    folder: "docs/blogs/css" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fileName}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "FILE Name", name: "fileName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "javascript" # Used in routes, e.g., /admin/collections/blog
    label: "Doc/javascript" # Used in the UI
    folder: "docs/blogs/javascript" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fileName}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "FILE Name", name: "fileName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "Doc/about" # Used in the UI
    folder: "docs/blogs/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fileName}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "FILE Name", name: "fileName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
